"""task2_pgvector_and_brain_tables

Revision ID: 1b57dd714afb
Revises: 
Create Date: 2026-05-04 19:11:06.591546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b57dd714afb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('brain_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['brain_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_chunks_company_id'), 'brain_chunks', ['company_id'], unique=False)
    op.create_index('ix_brain_chunks_company_superseded', 'brain_chunks', ['company_id', 'superseded_at'], unique=False)
    op.create_index('ix_brain_chunks_embedding_hnsw', 'brain_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('brain_customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_customers_company_id'), 'brain_customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_brain_customers_email'), 'brain_customers', ['email'], unique=False)
    op.create_index(op.f('ix_brain_customers_phone'), 'brain_customers', ['phone'], unique=False)
    op.create_table('brain_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_documents_company_id'), 'brain_documents', ['company_id'], unique=False)
    op.create_table('brain_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', 'subject', name='uq_brain_facts_company_key_subject')
    )
    op.create_index(op.f('ix_brain_facts_company_id'), 'brain_facts', ['company_id'], unique=False)
    op.create_table('brain_faqs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_faqs_company_id'), 'brain_faqs', ['company_id'], unique=False)
    op.create_index('ix_brain_faqs_embedding_hnsw', 'brain_faqs', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('brain_jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_jobs_company_id'), 'brain_jobs', ['company_id'], unique=False)
    op.create_table('brain_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_media_company_id'), 'brain_media', ['company_id'], unique=False)
    op.create_table('brain_media_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('trigger_topic', sa.Text(), nullable=True),
    sa.Column('trigger_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('trigger_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('media_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('caption_template', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_media_triggers_company_id'), 'brain_media_triggers', ['company_id'], unique=False)
    op.create_table('brain_persona',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tone', sa.Text(), server_default=sa.text("'friendly'"), nullable=False),
    sa.Column('addressing', sa.Text(), server_default=sa.text("'tykanie'"), nullable=False),
    sa.Column('language', sa.Text(), server_default=sa.text("'sk'"), nullable=False),
    sa.Column('emoji_use', sa.Text(), server_default=sa.text("'sometimes'"), nullable=False),
    sa.Column('length_preference', sa.Text(), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('negative_facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_brain_persona_company')
    )
    op.create_table('brain_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('message_count_at_summary', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_summaries_company_id'), 'brain_summaries', ['company_id'], unique=False)
    op.create_index(op.f('ix_brain_summaries_conversation_id'), 'brain_summaries', ['conversation_id'], unique=False)
    op.create_table('brain_tuning_changes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('owner_message', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('target_table', sa.Text(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('diff_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_tuning_changes_company_id'), 'brain_tuning_changes', ['company_id'], unique=False)
    op.create_table('brain_customer_memory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['brain_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_customer_memory_customer_id'), 'brain_customer_memory', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brain_customer_memory_customer_id'), table_name='brain_customer_memory')
    op.drop_table('brain_customer_memory')
    op.drop_index(op.f('ix_brain_tuning_changes_company_id'), table_name='brain_tuning_changes')
    op.drop_table('brain_tuning_changes')
    op.drop_index(op.f('ix_brain_summaries_conversation_id'), table_name='brain_summaries')
    op.drop_index(op.f('ix_brain_summaries_company_id'), table_name='brain_summaries')
    op.drop_table('brain_summaries')
    op.drop_table('brain_persona')
    op.drop_index(op.f('ix_brain_media_triggers_company_id'), table_name='brain_media_triggers')
    op.drop_table('brain_media_triggers')
    op.drop_index(op.f('ix_brain_media_company_id'), table_name='brain_media')
    op.drop_table('brain_media')
    op.drop_index(op.f('ix_brain_jobs_company_id'), table_name='brain_jobs')
    op.drop_table('brain_jobs')
    op.drop_index('ix_brain_faqs_embedding_hnsw', table_name='brain_faqs', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_brain_faqs_company_id'), table_name='brain_faqs')
    op.drop_table('brain_faqs')
    op.drop_index(op.f('ix_brain_facts_company_id'), table_name='brain_facts')
    op.drop_table('brain_facts')
    op.drop_index(op.f('ix_brain_documents_company_id'), table_name='brain_documents')
    op.drop_table('brain_documents')
    op.drop_index(op.f('ix_brain_customers_phone'), table_name='brain_customers')
    op.drop_index(op.f('ix_brain_customers_email'), table_name='brain_customers')
    op.drop_index(op.f('ix_brain_customers_company_id'), table_name='brain_customers')
    op.drop_table('brain_customers')
    op.drop_index('ix_brain_chunks_embedding_hnsw', table_name='brain_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_brain_chunks_company_superseded', table_name='brain_chunks')
    op.drop_index(op.f('ix_brain_chunks_company_id'), table_name='brain_chunks')
    op.drop_table('brain_chunks')
    # ### end Alembic commands ###
