"""add audit_logs

Revision ID: 1e3cd1011453
Revises: 4405e98e492a
Create Date: 2026-05-04 21:13:36.636597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e3cd1011453'
down_revision: Union[str, None] = '4405e98e492a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('retrieved_chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('retrieved_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cited_sources', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('used_chunk_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('needs_human', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_company_created', 'audit_logs', ['company_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
