"""add content_hash to brain_chunks

Revision ID: 4405e98e492a
Revises: 1b57dd714afb
Create Date: 2026-05-04 20:49:59.939216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4405e98e492a'
down_revision: Union[str, None] = '1b57dd714afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brain_chunks', sa.Column('content_hash', sa.Text(), nullable=True))
    op.create_index('uq_brain_chunks_company_hash_active', 'brain_chunks', ['company_id', 'content_hash'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_brain_chunks_company_hash_active', table_name='brain_chunks', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_column('brain_chunks', 'content_hash')
    # ### end Alembic commands ###
