"""coach: audit_logs proposal columns

Revision ID: eba2b4ef7fe9
Revises: 1e3cd1011453
Create Date: 2026-05-04 22:00:26.949802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eba2b4ef7fe9'
down_revision: Union[str, None] = '1e3cd1011453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('intent', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('proposal_hash', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('diff_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('diff_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('actor', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.Text(), nullable=True))
    op.create_index('uq_audit_logs_company_proposal_hash', 'audit_logs', ['company_id', 'proposal_hash'], unique=True, postgresql_where=sa.text('proposal_hash IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_audit_logs_company_proposal_hash', table_name='audit_logs', postgresql_where=sa.text('proposal_hash IS NOT NULL'))
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'diff_after')
    op.drop_column('audit_logs', 'diff_before')
    op.drop_column('audit_logs', 'proposal')
    op.drop_column('audit_logs', 'proposal_hash')
    op.drop_column('audit_logs', 'intent')
    # ### end Alembic commands ###
