"""HDS-v3 operating manual persona document model.

Distinct from `brain_persona` (singular) which holds chatbot style config
(tone/addressing/emoji). This table stores the 2000-word operating manual
generated by Gemini from extracted website content — used as RAG context
for AI conversations.
"""
import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import BigInteger, DateTime, Integer, Numeric, Text, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class BrainPersonaDocument(Base):
    __tablename__ = "brain_personas"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    company_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    version: Mapped[int] = mapped_column(
        Integer, server_default=text("1"), nullable=False
    )
    persona_text: Mapped[str] = mapped_column(Text, nullable=False)
    word_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    source_urls: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    gemini_cost_usd: Mapped[Decimal | None] = mapped_column(
        Numeric(10, 6), server_default=text("0"), nullable=True
    )
    tokens_in: Mapped[int | None] = mapped_column(
        Integer, server_default=text("0"), nullable=True
    )
    tokens_out: Mapped[int | None] = mapped_column(
        Integer, server_default=text("0"), nullable=True
    )
    meta: Mapped[dict | None] = mapped_column(
        JSONB, server_default=text("'{}'::jsonb"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
